### ISSUE TITLE
Add into the vim-airline-themes repository

### ISSUE THREAD

**Issue by halfa** [everard/vim-aurora-theme#1]
You can submit the airline-theme to the official repository [here](https://github.com/vim-airline/vim-airline-themes) to avoid any additional step. You can also submit the theme itself [on this repo](https://github.com/flazz/vim-colorschemes). I think it's a really nice alternative to `papercolor`! :smiley:

**Comment by everard** [comment]
Oh, sorry, didn't see your comment! Ok, I'll try. =)

**Comment by everard** [comment]
I've submitted theme to repositories. Thank you! :)
